# Site settings
title: Daydream Store
description: Accesorios personalizados. <a href="http://html5up.net">HTML5 UP</a>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dayanaquirozaraujo.github.io"
author: Dayana Vanessa Quiroz Araujo

# Collection settings
collections:
  photos:

# Social settings
#500px_url:
facebook_url: https://www.facebook.com/daydream.store25
#github_url:
#gitlab_url: 
#googleplus_url:
instagram_url:https://instagram.com/daydream.store_?utm_medium=copy_link
#linkedin_url:
#pinterest_url:
#slack_url:
#twitter_url:

# Build settings
markdown: kramdown
